name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/firestore-credentials.json

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - name: Install Dependencies
        run: npm ci
        working-directory: ./functions

      - name: Setup firestore-credentials.json
        run: |
          echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}' >> ${{ github.workspace }}/firestore-credentials.json

      - name: Deploy
        run: npm run deploy
        working-directory: ./functions
