name: Tests

on: [pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci
        working-directory: ./functions

      - name: Unit Tests
        run: npm run test
        working-directory: ./functions
