name: Tests

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - name: Install Dependencies
        run: npm ci
        working-directory: ./functions

      - name: Setup firestore-credentials.json
        run: |
          printf '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}' >> ${{ github.workspace }}/firestore-credentials.json

      - name: Setup .env.test file
        run: |
          printf "GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/firestore-credentials.json" >> .env.test
          printf "OPEN_AI_KEY=${{ secrets.OPEN_AI_KEY }}" >> .env.test

      - name: Unit Tests
        run: npm run test
        working-directory: ./functions
