name: Tests

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/firestore-credentials.json
      OPEN_AI_KEY: ${{ secrets.OPEN_AI_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - name: Install Dependencies
        run: npm ci
        working-directory: ./functions

      - name: Setup firestore-credentials.json
        run: |
          echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}' >> ${{ github.workspace }}/firestore-credentials.json

      - name: Unit Tests
        run: npm run test:ci
        working-directory: ./functions
